In [3]:
import pandas as pd
books = pd.read_csv('booklist.csv')
books.head(5)

                                               title
0  The Choice: Embrace the Possible by Dr. Edith ...
1                      Cloud Atlas by David Mitchell
2              The Ride of a Lifetime by Robert Iger
3               The Great Influenza by John M. Barry
4  Good Economics For Hard Times by Abhijit V. Ba...

In [10]:
books[['book', 'author']] = books['title'].str.split('by', expand=True)
books.sample(10)

,title,book,author
97,Behind the Beautiful Forevers by Katherine Boo,Behind the Beautiful Forevers,Katherine Boo
101,The Man Who Stayed Behind by Amanda Bennett,The Man Who Stayed Behind,Amanda Bennett
20,Bad Blood by John Carreyrou,Bad Blood,John Carreyrou
30,"Believe Me: A Memoir of Love, Death, and Jazz ...","Believe Me: A Memoir of Love, Death, and Jazz ...",Eddie Izzard
93,The Better Angels of Our Nature by Steven Pinker,The Better Angels of Our Nature,Steven Pinker
42,The Grid by Gretchen Bakke,The Grid,Gretchen Bakke
43,Seveneves by Neal Stephenson,Seveneves,Neal Stephenson
26,Origin Story: A Big History of Everything by D...,Origin Story: A Big History of Everything,David Christian
48,The Road to Character by David Brooks,The Road to Character,David Brooks
65,Business Adventures by John Brooks.,Business Adventures,John Brooks.

In [11]:
books.to_csv('output_file.csv', index=False)